In [89]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [90]:
import numpy as np

In [91]:
RevenueArray=np.array(revenue)
ExpenseArray=np.array(expenses)

In [92]:
#Finding the Profir
Profit=RevenueArray-ExpenseArray

In [93]:
Profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [94]:
#Finding Profit After Tax (Tax=30%)
ProfitAfterTax=Profit-Profit*0.3

In [95]:
ProfitAfterTax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [96]:
#Finding Profit Margin
ProfitMargin=ProfitAfterTax/RevenueArray

In [97]:
ProfitMargin

array([ 0.12116163,  0.17589956, -0.30139698, -0.22233524, -0.05211096,
        0.62743886,  0.49993433,  0.28276199,  0.22608449, -0.10897492,
        0.04309514,  0.52746804])

In [98]:
ProfitMargin=ProfitMargin*100

In [99]:
ProfitMargin

array([ 12.11616324,  17.58995643, -30.13969838, -22.23352417,
        -5.21109615,  62.74388559,  49.99343266,  28.27619856,
        22.60844884, -10.89749207,   4.30951365,  52.74680403])

In [100]:
ProfitMargin=ProfitMargin.round(2)
ProfitMargin

array([ 12.12,  17.59, -30.14, -22.23,  -5.21,  62.74,  49.99,  28.28,
        22.61, -10.9 ,   4.31,  52.75])

In [101]:
#Calculating the Mean Value
MeanValue=ProfitAfterTax.mean()

In [102]:
MeanValue

1750.6813333333332

In [103]:
#good months - where the profit after tax was greater than the mean for the year
GoodMonths=ProfitAfterTax>MeanValue

In [104]:
GoodMonths

array([ True, False, False, False, False,  True,  True,  True,  True,
       False, False,  True])

In [105]:
#bad months - where the profit after tax was less than the mean for the year
BadMonths=ProfitAfterTax<=MeanValue
BadMonths

array([False,  True,  True,  True,  True, False, False, False, False,
        True,  True, False])

In [106]:
MaxValue=ProfitAfterTax.max()

In [107]:
#the best month - where the profit after tax was max for the year
BestMonth=ProfitAfterTax == MaxValue

In [108]:
BestMonth

array([False, False, False, False, False, False, False, False, False,
       False, False,  True])

In [109]:
#the worst month - where the profit after tax was min for the year
MinValue=ProfitAfterTax.min()
WorstMonth=ProfitAfterTax == MinValue
WorstMonth

array([False, False,  True, False, False, False, False, False, False,
       False, False, False])